# Etapa 1: Construcción
FROM node:18-alpine AS builder
WORKDIR /app

# Copiar archivos de configuración y bajar dependencias
COPY package.json package-lock.json ./
RUN npm install --frozen-lockfile

# Copiar el código fuente y construir el proyecto
COPY . .
RUN npm run build

# Define la salida de la build
CMD ["echo", "Build completado. Usa el contenedor de Nginx para servir los archivos."]

