services:
  db:
    image: mysql:8
    container_name: mysql_tours
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: terranova_db
      MYSQL_USER: terranova
      MYSQL_PASSWORD: terranova
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  backend:
    build: ./backend/terranova
    container_name: backend_tours
    restart: always
    depends_on:
      - db
    env_file:
      - ./backend/terranova/.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/terranova_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: terranova
      SPRING_DATASOURCE_PASSWORD: terranova
    ports:
      - "8080:8080"
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
