version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mysql_tours
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: terranova_db
    ports:
      - "3307:3306" # Cambia el puerto externo a 3307 ya que en mi local se encuentra ocupado
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend/terranova
    container_name: backend_tours
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/terranova_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: frontend_tours
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:
