# CONFIGURACIÓN GENERAL DE SPRING
spring.application.name=terranova
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

# CONFIGURACIÓN PARA H2 (DESARROLLO LOCAL)
spring.profiles.active=local  # Usa H2 por defecto en desarrollo

---
# CONFIGURACIÓN PARA H2 (PERFIL LOCAL)
spring.config.activate.on-profile=local
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:terranova
spring.datasource.username=sa
spring.datasource.password=sa
spring.h2.console.enabled=true  # Habilita la consola en http://localhost:8080/h2-console
---

# CONFIGURACIÓN PARA MySQL (CUANDO SE USE DOCKER O EL DESPLIEGUE)
spring.config.activate.on-profile=docker
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://db:3306/terranova_db
spring.datasource.username=root
spring.datasource.password=root