spring:
  application:
    name: terranova

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/terranova_db?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: terranova
    password: terranova
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1200000
      connection-timeout: 20000

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        connection:
          characterEncoding: UTF-8
          useUnicode: true

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
