# CONFIGURACIÓN GENERAL DE SPRING
spring.application.name=terranova
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

# CONFIGURACIÓN PARA H2 (SI SE USA application.properties)
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:terranova
spring.datasource.username=sa
spring.datasource.password=sa
spring.h2.console.enabled=true  # Habilita la consola en http://localhost:8080/h2-console